name: Doxygen

on:
  push:
    paths:
      - '.github/workflows/doxygen.yml'
      - 'doxygen/**'
      - '!doxygen/*.md'
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      pkgname: ipxe-doxygen
      reponame: ghcr.io/${{ github.repository_owner }}
      label: ${{ github.ref_name == 'master' && 'latest' || github.ref_name }}
    steps:

      - name: Check out code
        uses: actions/checkout@v6

      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up builder
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: doxygen
          push: true
          tags: |
            ${{ env.reponame }}/${{ env.pkgname }}:draft-${{ github.sha }}

      - name: Build (checker)
        uses: docker/build-push-action@v6
        with:
          context: doxygen
          target: check-doxygen
          push: false
          load: true
          tags: |
            check-doxygen

      - name: Test
        run: |
          docker run --rm check-doxygen

      - name: Publish
        run: |
          docker buildx imagetools create \
            --tag ${{ env.reponame }}/${{ env.pkgname }}:${{ env.label }} \
            ${{ env.reponame }}/${{ env.pkgname }}:draft-${{ github.sha }}
