name: Signer

on:
  push:
    paths:
      - '.github/workflows/signer.yml'
      - 'signer/**'
      - '!signer/*.md'
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      pkgname: ipxe-signer
      reponame: ghcr.io/${{ github.repository_owner }}
      label: ${{ github.ref_name == 'master' && 'latest' || github.ref_name }}
    steps:

      - name: Check out code
        uses: actions/checkout@v6

      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up builder
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: signer
          push: true
          tags: |
            ${{ env.reponame }}/${{ env.pkgname }}:draft-${{ github.sha }}
            ${{ env.reponame }}/${{ env.pkgname }}:${{ env.label }}
