name: Sysroot (loong64)

on:
  push:
    paths:
      - '.github/workflows/sysroot.yml'
      - '.github/workflows/sysroot_loong64.yml'
      - 'sysroot/**'
      - '!sysroot/*.md'
      - '!sysroot/configs/**'
      - 'sysroot/configs/sysroot_loong64_defconfig'
  workflow_dispatch:

jobs:

  build:
    name: Build (loong64)
    uses: ./.github/workflows/sysroot.yml
    with:
      arch: loong64
